-- Tabla para resúmenes mensuales
CREATE TABLE IF NOT EXISTS public.resumen_mensual_cuentas (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  idcuenta BIGINT REFERENCES public.cuenta(id) ON DELETE CASCADE,
  idusuario BIGINT REFERENCES public.usuarios(id) ON DELETE CASCADE,
  anio INT NOT NULL,
  mes INT NOT NULL,
  ingresos NUMERIC DEFAULT 0,
  gastos NUMERIC DEFAULT 0,
  balance NUMERIC DEFAULT 0,
  UNIQUE(idcuenta, anio, mes)
);

-- Función para recalcular un mes específico de una cuenta
-- Soporta tipos 'i', 'g' y 't' (transferencias)
CREATE OR REPLACE FUNCTION public.fn_recalcular_mes_cuenta(p_idcuenta BIGINT, p_anio INT, p_mes INT)
RETURNS VOID
LANGUAGE plpgsql
AS $$
DECLARE
  v_idusuario BIGINT;
  v_fecha_inicio DATE;
  v_fecha_fin DATE;
BEGIN
  SELECT idusuario INTO v_idusuario FROM public.cuenta WHERE id = p_idcuenta;

  -- Definir rango de fechas para el mes (Sargable para índices)
  v_fecha_inicio := make_date(p_anio, p_mes, 1);
  v_fecha_fin := v_fecha_inicio + interval '1 month';

  IF v_idusuario IS NOT NULL THEN
    INSERT INTO public.resumen_mensual_cuentas (idcuenta, idusuario, anio, mes, ingresos, gastos, balance)
    SELECT
      p_idcuenta,
      v_idusuario,
      p_anio,
      p_mes,
      -- Ingresos: solo movimientos tipo 'i'
      COALESCE(SUM(CASE WHEN tipo = 'i' AND idcuenta = p_idcuenta THEN valor ELSE 0 END), 0),
      -- Gastos: solo movimientos tipo 'g'
      COALESCE(SUM(CASE WHEN tipo = 'g' AND idcuenta = p_idcuenta THEN valor ELSE 0 END), 0),
      -- Balance: ingresos - gastos + transferencias entrantes - transferencias salientes
      COALESCE(SUM(CASE
        WHEN tipo = 'i' AND idcuenta = p_idcuenta THEN valor
        WHEN tipo = 'g' AND idcuenta = p_idcuenta THEN -valor
        WHEN tipo = 't' AND idcuenta_destino = p_idcuenta THEN valor
        WHEN tipo = 't' AND idcuenta_origen = p_idcuenta THEN -valor
        ELSE 0
      END), 0)
    FROM public.movimientos
    WHERE (
      (tipo IN ('i', 'g') AND idcuenta = p_idcuenta)
      OR
      (tipo = 't' AND (idcuenta_origen = p_idcuenta OR idcuenta_destino = p_idcuenta))
    )
      AND fecha >= v_fecha_inicio
      AND fecha < v_fecha_fin
      AND estado = true
    ON CONFLICT (idcuenta, anio, mes)
    DO UPDATE SET
      ingresos = EXCLUDED.ingresos,
      gastos = EXCLUDED.gastos,
      balance = EXCLUDED.balance;
  END IF;
END;
$$;

-- Función para el trigger que actualiza el resumen mensual
-- Soporta tipos 'i', 'g' y 't' (transferencias)
CREATE OR REPLACE FUNCTION public.fn_actualizar_resumen_mensual()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
  -- Si es UPDATE, actualizar cuentas afectadas por el registro ANTERIOR
  IF (TG_OP = 'UPDATE') THEN
    IF OLD.tipo IN ('i', 'g') THEN
      IF (OLD.idcuenta IS DISTINCT FROM NEW.idcuenta OR OLD.fecha IS DISTINCT FROM NEW.fecha OR OLD.estado IS DISTINCT FROM NEW.estado) THEN
        IF OLD.idcuenta IS NOT NULL AND OLD.fecha IS NOT NULL THEN
          PERFORM public.fn_recalcular_mes_cuenta(OLD.idcuenta, EXTRACT(YEAR FROM OLD.fecha)::INT, EXTRACT(MONTH FROM OLD.fecha)::INT);
        END IF;
      END IF;
    ELSIF OLD.tipo = 't' THEN
      IF (OLD.idcuenta_origen IS DISTINCT FROM NEW.idcuenta_origen OR OLD.idcuenta_destino IS DISTINCT FROM NEW.idcuenta_destino OR OLD.fecha IS DISTINCT FROM NEW.fecha OR OLD.estado IS DISTINCT FROM NEW.estado) THEN
        IF OLD.idcuenta_origen IS NOT NULL AND OLD.fecha IS NOT NULL THEN
          PERFORM public.fn_recalcular_mes_cuenta(OLD.idcuenta_origen, EXTRACT(YEAR FROM OLD.fecha)::INT, EXTRACT(MONTH FROM OLD.fecha)::INT);
        END IF;
        IF OLD.idcuenta_destino IS NOT NULL AND OLD.fecha IS NOT NULL THEN
          PERFORM public.fn_recalcular_mes_cuenta(OLD.idcuenta_destino, EXTRACT(YEAR FROM OLD.fecha)::INT, EXTRACT(MONTH FROM OLD.fecha)::INT);
        END IF;
      END IF;
    END IF;
  END IF;

  -- Actualizar el registro nuevo/actual
  IF (TG_OP = 'DELETE') THEN
    IF OLD.tipo IN ('i', 'g') AND OLD.idcuenta IS NOT NULL AND OLD.fecha IS NOT NULL THEN
      PERFORM public.fn_recalcular_mes_cuenta(OLD.idcuenta, EXTRACT(YEAR FROM OLD.fecha)::INT, EXTRACT(MONTH FROM OLD.fecha)::INT);
    ELSIF OLD.tipo = 't' AND OLD.fecha IS NOT NULL THEN
      IF OLD.idcuenta_origen IS NOT NULL THEN
        PERFORM public.fn_recalcular_mes_cuenta(OLD.idcuenta_origen, EXTRACT(YEAR FROM OLD.fecha)::INT, EXTRACT(MONTH FROM OLD.fecha)::INT);
      END IF;
      IF OLD.idcuenta_destino IS NOT NULL THEN
        PERFORM public.fn_recalcular_mes_cuenta(OLD.idcuenta_destino, EXTRACT(YEAR FROM OLD.fecha)::INT, EXTRACT(MONTH FROM OLD.fecha)::INT);
      END IF;
    END IF;
  ELSE
    -- INSERT o UPDATE (NEW)
    IF NEW.tipo IN ('i', 'g') AND NEW.idcuenta IS NOT NULL AND NEW.fecha IS NOT NULL THEN
      PERFORM public.fn_recalcular_mes_cuenta(NEW.idcuenta, EXTRACT(YEAR FROM NEW.fecha)::INT, EXTRACT(MONTH FROM NEW.fecha)::INT);
    ELSIF NEW.tipo = 't' AND NEW.fecha IS NOT NULL THEN
      IF NEW.idcuenta_origen IS NOT NULL THEN
        PERFORM public.fn_recalcular_mes_cuenta(NEW.idcuenta_origen, EXTRACT(YEAR FROM NEW.fecha)::INT, EXTRACT(MONTH FROM NEW.fecha)::INT);
      END IF;
      IF NEW.idcuenta_destino IS NOT NULL THEN
        PERFORM public.fn_recalcular_mes_cuenta(NEW.idcuenta_destino, EXTRACT(YEAR FROM NEW.fecha)::INT, EXTRACT(MONTH FROM NEW.fecha)::INT);
      END IF;
    END IF;
  END IF;

  RETURN NULL;
END;
$$;

-- Trigger para mantener la tabla de resúmenes actualizada
DROP TRIGGER IF EXISTS trg_actualizar_resumen_mensual ON public.movimientos;
CREATE TRIGGER trg_actualizar_resumen_mensual
AFTER INSERT OR UPDATE OR DELETE ON public.movimientos
FOR EACH ROW
EXECUTE FUNCTION public.fn_actualizar_resumen_mensual();

-- Función para calcular el saldo de una cuenta hasta una fecha determinada (excluyendo esa fecha)
-- Incluye el efecto de las transferencias (tipo 't')
CREATE OR REPLACE FUNCTION public.fn_obtener_saldo_cuenta_a_fecha(p_idcuenta BIGINT, p_fecha DATE)
RETURNS NUMERIC
LANGUAGE plpgsql
AS $$
DECLARE
  v_saldo NUMERIC;
BEGIN
  SELECT COALESCE(SUM(CASE
    WHEN tipo = 'i' AND idcuenta = p_idcuenta THEN valor
    WHEN tipo = 'g' AND idcuenta = p_idcuenta THEN -valor
    WHEN tipo = 't' AND idcuenta_destino = p_idcuenta THEN valor
    WHEN tipo = 't' AND idcuenta_origen = p_idcuenta THEN -valor
    ELSE 0
  END), 0)
  INTO v_saldo
  FROM public.movimientos
  WHERE (
    (tipo IN ('i', 'g') AND idcuenta = p_idcuenta)
    OR
    (tipo = 't' AND (idcuenta_origen = p_idcuenta OR idcuenta_destino = p_idcuenta))
  )
    AND fecha < p_fecha
    AND estado = true;

  RETURN v_saldo;
END;
$$;

-- Poblar tabla inicial con datos existentes
INSERT INTO public.resumen_mensual_cuentas (idcuenta, idusuario, anio, mes, ingresos, gastos, balance)
SELECT
  m.idcuenta,
  c.idusuario,
  EXTRACT(YEAR FROM m.fecha)::INT as anio_val,
  EXTRACT(MONTH FROM m.fecha)::INT as mes_val,
  SUM(CASE WHEN m.tipo = 'i' THEN m.valor ELSE 0 END) as ingresos,
  SUM(CASE WHEN m.tipo = 'g' THEN m.valor ELSE 0 END) as gastos,
  SUM(CASE WHEN m.tipo = 'i' THEN m.valor ELSE -m.valor END) as balance
FROM public.movimientos m
JOIN public.cuenta c ON m.idcuenta = c.id
WHERE m.estado = true
  AND m.fecha IS NOT NULL
  AND m.idcuenta IS NOT NULL
GROUP BY m.idcuenta, c.idusuario, EXTRACT(YEAR FROM m.fecha), EXTRACT(MONTH FROM m.fecha)
ON CONFLICT (idcuenta, anio, mes) DO UPDATE SET
  ingresos = EXCLUDED.ingresos,
  gastos = EXCLUDED.gastos,
  balance = EXCLUDED.balance;
