-- Tabla para resúmenes mensuales
CREATE TABLE IF NOT EXISTS public.resumen_mensual_cuentas (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  idcuenta BIGINT REFERENCES public.cuenta(id) ON DELETE CASCADE,
  idusuario BIGINT REFERENCES public.usuarios(id) ON DELETE CASCADE,
  anio INT NOT NULL,
  mes INT NOT NULL,
  ingresos NUMERIC DEFAULT 0,
  gastos NUMERIC DEFAULT 0,
  balance NUMERIC DEFAULT 0,
  UNIQUE(idcuenta, anio, mes)
);

-- Función para recalcular un mes específico de una cuenta
CREATE OR REPLACE FUNCTION public.fn_recalcular_mes_cuenta(p_idcuenta BIGINT, p_anio INT, p_mes INT)
RETURNS VOID
LANGUAGE plpgsql
AS $$
DECLARE
  v_idusuario BIGINT;
BEGIN
  SELECT idusuario INTO v_idusuario FROM public.cuenta WHERE id = p_idcuenta;

  IF v_idusuario IS NOT NULL THEN
    INSERT INTO public.resumen_mensual_cuentas (idcuenta, idusuario, anio, mes, ingresos, gastos, balance)
    SELECT
      p_idcuenta,
      v_idusuario,
      p_anio,
      p_mes,
      COALESCE(SUM(CASE WHEN tipo = 'i' THEN valor ELSE 0 END), 0),
      COALESCE(SUM(CASE WHEN tipo = 'g' THEN valor ELSE 0 END), 0),
      COALESCE(SUM(CASE WHEN tipo = 'i' THEN valor ELSE -valor END), 0)
    FROM public.movimientos
    WHERE idcuenta = p_idcuenta
      AND EXTRACT(YEAR FROM fecha) = p_anio
      AND EXTRACT(MONTH FROM fecha) = p_mes
      AND estado = true
    ON CONFLICT (idcuenta, anio, mes)
    DO UPDATE SET
      ingresos = EXCLUDED.ingresos,
      gastos = EXCLUDED.gastos,
      balance = EXCLUDED.balance;
  END IF;
END;
$$;

-- Función para el trigger que actualiza el resumen mensual
CREATE OR REPLACE FUNCTION public.fn_actualizar_resumen_mensual()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
  -- Si es UPDATE y cambió cuenta o fecha o estado, actualizar el registro antiguo
  IF (TG_OP = 'UPDATE') THEN
     IF (OLD.idcuenta <> NEW.idcuenta OR OLD.fecha <> NEW.fecha OR OLD.estado <> NEW.estado) THEN
        PERFORM public.fn_recalcular_mes_cuenta(OLD.idcuenta, EXTRACT(YEAR FROM OLD.fecha)::INT, EXTRACT(MONTH FROM OLD.fecha)::INT);
     END IF;
  END IF;

  -- Actualizar el registro nuevo/actual
  IF (TG_OP = 'DELETE') THEN
     PERFORM public.fn_recalcular_mes_cuenta(OLD.idcuenta, EXTRACT(YEAR FROM OLD.fecha)::INT, EXTRACT(MONTH FROM OLD.fecha)::INT);
  ELSE
     PERFORM public.fn_recalcular_mes_cuenta(NEW.idcuenta, EXTRACT(YEAR FROM NEW.fecha)::INT, EXTRACT(MONTH FROM NEW.fecha)::INT);
  END IF;

  RETURN NULL;
END;
$$;

-- Trigger para mantener la tabla de resúmenes actualizada
DROP TRIGGER IF EXISTS trg_actualizar_resumen_mensual ON public.movimientos;
CREATE TRIGGER trg_actualizar_resumen_mensual
AFTER INSERT OR UPDATE OR DELETE ON public.movimientos
FOR EACH ROW
EXECUTE FUNCTION public.fn_actualizar_resumen_mensual();

-- Función para calcular el saldo de una cuenta hasta una fecha determinada (excluyendo esa fecha)
CREATE OR REPLACE FUNCTION public.fn_obtener_saldo_cuenta_a_fecha(p_idcuenta BIGINT, p_fecha DATE)
RETURNS NUMERIC
LANGUAGE plpgsql
AS $$
DECLARE
  v_saldo NUMERIC;
BEGIN
  SELECT COALESCE(SUM(CASE WHEN tipo = 'i' THEN valor ELSE -valor END), 0)
  INTO v_saldo
  FROM public.movimientos
  WHERE idcuenta = p_idcuenta
    AND fecha < p_fecha
    AND estado = true;

  RETURN v_saldo;
END;
$$;

-- Poblar tabla inicial con datos existentes
INSERT INTO public.resumen_mensual_cuentas (idcuenta, idusuario, anio, mes, ingresos, gastos, balance)
SELECT
  m.idcuenta,
  c.idusuario,
  EXTRACT(YEAR FROM m.fecha)::INT as anio,
  EXTRACT(MONTH FROM m.fecha)::INT as mes,
  SUM(CASE WHEN m.tipo = 'i' THEN m.valor ELSE 0 END) as ingresos,
  SUM(CASE WHEN m.tipo = 'g' THEN m.valor ELSE 0 END) as gastos,
  SUM(CASE WHEN m.tipo = 'i' THEN m.valor ELSE -m.valor END) as balance
FROM public.movimientos m
JOIN public.cuenta c ON m.idcuenta = c.id
WHERE m.estado = true
GROUP BY m.idcuenta, c.idusuario, anio, mes
ON CONFLICT (idcuenta, anio, mes) DO UPDATE SET
  ingresos = EXCLUDED.ingresos,
  gastos = EXCLUDED.gastos,
  balance = EXCLUDED.balance;
